@default_files = ('main.tex');
$pdf_mode = 5;
$out_dir = 'build';
$xelatex = 'xelatex -file-line-error -halt-on-error -interaction=nonstopmode -no-pdf -synctex=1 %O %S';
$xdvipdfmx = 'xdvipdfmx -q -E -o %D %O %S';
$bibtex_use = 1.5;
